##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2],[3,4],[5,6]])
print(f"Araay 1 : {arr}")
print(f"Array 2 : {arr2}")
#1. number of rows and no. of columns
print(f'The shape of the array 1 is {arr.shape}')
print(f'The shape of the array 2 is {arr2.shape}')

#2. we have check dimensions of the array
print(f'The dimension of the array 1 is {arr.ndim}')
print(f'The dimension of the array 2 is {arr2.ndim}')

#3. If we have check total number of elements present in your array
print(f'The size of the array 1 is {arr.ndim}')
print(f'The size of the array 2 is {arr2.ndim}')

#4. check the the data type of the array
print(f'The type of the array 1 is {arr.dtype}')
print(f'The type of the array 2 is {arr2.dtype}')





Araay 1 : [1 2 3 4 5]
Array 2 : [[1 2]
 [3 4]
 [5 6]]
The shape of the array 1 is (5,)
The shape of the array 2 is (3, 2)
The dimension of the array 1 is 1
The dimension of the array 2 is 2
The size of the array 1 is 1
The size of the array 2 is 2
The type of the array 1 is int64
The type of the array 2 is int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
arr[1]

np.int64(2)

In [ ]:
# silicing. [start(0):stop:step(1)]
print(arr[1:4])
print(arr)


[2 3 4]
[1 2 3 4 5]


Now lets see the 2D indexing aswell

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#matrix[row_index , col_index]
print(matrix[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


Now we can also do the slicing lets see the **slicing in 1D**

1D slicing was really easy now lets see the **slicing in 2D**

In [ ]:
matrix
#matrix[r_s_index:r_stop_index,c_s_index:c-stop_index]
print(matrix)
matrix[1:3,1:3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

There is one more thing known as **Boolean indexing**

In [ ]:
arr = np.array([5,10,15,18,20,22])
arr < 18 #boolen needed( shape,matrix sizing boolen indexing are imp )
arr[arr < 18]

array([ 5, 10, 15])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [3]:
import numpy as np
arr = np.arange(1,11)
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])