# **Using NumPy**

Once you've installed NumPy you can import it as a library:

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [1]:
import numpy as np

l = [1,2,3,4,5]
arr = np.array(l)
print(arr * 5)

[ 5 10 15 20 25]


Lets create a matrix using list

In [2]:
l = [[1,2,3,4],[5,6,7,8]]
arr = np.array(l)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [3]:
arr = np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [4]:
print(np.zeros([4,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
arr = np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [6]:
arr = np.ones([2,2])
print(arr)

[[1. 1.]
 [1. 1.]]


In [7]:
arr = np.full(5,7)
print(arr)

[7 7 7 7 7]


In [8]:
arr = np.arange(0,10,1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
arr = np.random.rand(2,3)
print(arr)

[[0.49946067 0.33887592 0.76878883]
 [0.13323684 0.14855695 0.28968982]]


In [13]:
arr = np.random.randint(1,10,(3,3))
print(arr)

[[5 9 5]
 [9 2 3]
 [1 3 4]]


In [14]:
arr = np.random.randn(2,4)
print(arr)

[[-0.10669601 -0.57681289  0.71234404 -0.313975  ]
 [ 0.37039685  1.12568774 -1.57314146 -0.52770201]]


arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution