##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [3]:
#some basis arthematic opertion
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(f"Addition of two array {arr1 + arr2}")
print(f"substraction of two array {arr1 - arr2}")
print(f"multiplication of two array {arr1 * arr2}")
print(f"division of two array {arr1 / arr2}")

Addition of two array [ 6  8 10 12]
substraction of two array [-4 -4 -4 -4]
multiplication of two array [ 5 12 21 32]
division of two array [0.2        0.33333333 0.42857143 0.5       ]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [4]:
#Array broadcasting
arr1 * 5

array([ 5, 10, 15, 20])

Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [5]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,1,1],[2,2,2],[3,3,3]])
A+B

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [6]:
arr = np.array([4,8,15,16,23,42])
print(f"Sum of arr is {arr.sum()}")
print(f"Mean of arr is {arr.mean()}")
print(f"Max of arr is {arr.max()}")
print(f"Min of arr is {arr.min()}")

Sum of arr is 108
Mean of arr is 18.0
Max of arr is 42
Min of arr is 4


You can also do the axis based operations row-Wise and Colum-wise

In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
matrix.sum(axis=1) #Axis = 1 for rows
matrix.sum(axis=0) #Axis = 0 for columns

array([12, 15, 18])

In [9]:
#sort takes place on the elements
arr = np.array([5,6,1,2,0])
print(np.sort(arr))

[0 1 2 5 6]


In [12]:
#argsort -> if we have to sort index first
print(np.argsort(arr))
index = np.argsort(arr)
print("Indexs",index)
print("Elements after sort",arr[index])

[4 2 3 0 1]
Indexs [4 2 3 0 1]
Elements after sort [0 1 2 5 6]
