##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
arr * 5 #Broadcasting

array([ 5, 10, 15, 20, 25, 30, 35])

In [ ]:
arr[[5,6]] #fancy indexing

array([6, 7])

In [ ]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
matrix
print(matrix[2:,2 :])

[[11 12]
 [15 16]]


In [ ]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
print(matrix[[0,0],[1,2]]) # [row(0,1)] [c(1,2)]
print(matrix[[1,1],[2,3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[2 3]
[7 8]


You can do this fancy indexing in 2D Matrix aswell

##Conditional Selection
Find values based on conditions or replace them.

In [ ]:
arr =np.array([1,2,50,23,12,13])
#replace a element where values are greater han 15
#Method 1
arr[arr > 15]

#Method 2
np.where(arr > 15,0,arr) # condition , kise pe replace , kahan se

array([ 1,  2,  0,  0, 12, 13])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

##Concatenation & Stacking

In [6]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a)
print(b)
np.concatenate([a,b])

[1 2 3 4]
[5 6 7 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
MatrixA = np.array([[1,2,3],[4,5,6]])
MatrixB = np.array([[1,1,1],[2,2,2]])
print(MatrixA)
print(MatrixB)
np.concatenate([MatrixA,MatrixB])

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [2 2 2]]


array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

Vertical & Horizontal Stacking

In [8]:
#Vertical stacking
np.vstack([MatrixA,MatrixB])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [2, 2, 2]])

In [9]:
#Horizontal stacking
np.hstack([MatrixA,MatrixB])

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 2, 2, 2]])

In [ ]:
#Important in numpy
#shape
#size
#descriptited statical function (mean,variance,std,max,min)
#.skew()