
# NumPy Assignment — Array Attributes, Indexing & Slicing



# Q1. Array Attributes

## Problem Statement
Create the following NumPy array:

```python
[10, 20, 30, 40, 50]
```

Print:
- Shape
- Number of Dimensions
- Size
- Data Type

## Sample Output
```python
Shape: (5,)
Dimensions: 1
Size: 5
dtype: int64
```


In [5]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(f"Shape {arr.shape}")
print(f"dimensions {arr.ndim}")
print(f"Size {arr.size}")
print(f"dtype {arr.dtype}")





Shape (5,)
dimensions 1
Size 5
dtype int64



# Q2. Find Array Shape

## Problem Statement
Create the following array:

```python
[[1,2,3],
 [4,5,6]]
```

Print only the shape of the array.

## Sample Output
```python
(2, 3)
```


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)



# Q3. 1D Indexing

## Problem Statement
Create the array:

```python
[5, 10, 15, 20, 25]
```

Print:
- First element
- Last element

## Sample Output
```python
5
25
```


In [7]:
arr = np.array([5,10,15,20,25])
print(arr[0])
print(arr[-1])

5
25



# Q4. 2D Indexing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the element `50`.

## Sample Output
```python
50
```


In [8]:
arr = np.array([[10,20,30],
 [40,50,60],
 [70,80,90]])
print(arr[1,1])

50



# Q5. 2D Indexing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the element `9`.

## Sample Output
```python
9
```


In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[2,2])

9



# Q6. 1D Slicing

## Problem Statement
Create the array:

```python
[10,20,30,40,50,60]
```

Print elements from index 1 to 4.

## Sample Output
```python
[20 30 40 50]
```


In [12]:
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])

[20, 30, 40, 50]



# Q7. 1D Slicing

## Problem Statement
Create the array:

```python
[1,2,3,4,5,6,7,8]
```

Print the first 5 elements.

## Sample Output
```python
[1 2 3 4 5]
```


In [15]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0:4])

[1 2 3 4]



# Q8. 2D Slicing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the first two rows.

## Sample Output
```python
[[1 2 3]
 [4 5 6]]
```


In [16]:
arr = np.array([[1,2,3],
 [4,5,6],
 [7,8,9]])
print(arr[:2])

[[1 2 3]
 [4 5 6]]



# Q9. 2D Slicing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the first two columns of all rows.

## Sample Output
```python
[[10 20]
 [40 50]
 [70 80]]
```


In [20]:
arr = np.array([[10,20,30],
 [40,50,60],
 [70,80,90]])
print(arr[:,:2])

[[10 20]
 [40 50]
 [70 80]]


# Q10. `np.eye()`

## Problem Statement
Using NumPy, create a **4 × 4 identity matrix** using the `np.eye()` function.

Print the resulting matrix.

## Sample Output
```python
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
```

In [21]:
matrix = np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Boolean Indexing (Practice)

**Q1.** Create a NumPy array from 1 to 20. Print only the elements greater than 10 using boolean indexing.



In [26]:
arr1 = np.arange(1,21)
result = arr1[arr1 > 10]
print(result)

[11 12 13 14 15 16 17 18 19 20]



**Q2.** Create the array:
```python
arr = np.array([12, 5, 18, 7, 25, 30, 2, 15])
```
Print only the even numbers using boolean indexing.


In [27]:
arr = np.array([12,5,18,7,25,30,2,151])
even = arr[arr % 2 == 0]
print(even)

[12 18 30  2]



**Q3.** Create a 4×4 random integer array (1–50). Print only the values greater than 25 using boolean indexing.


In [29]:
arr = np.random.randint(1,51,size = (4 ,4))
print(arr)
values = arr [arr > 25]
print(values)

[[45 31 16 32]
 [ 3 34 47 40]
 [26 13 48 19]
 [34 35 36 18]]
[45 31 32 34 47 40 26 48 34 35 36]
