# 📝 NumPy Assignment – Class 3

### Instructions
- Import NumPy as `np`.
- Solve each question in the code cell below it.
- Print the output wherever required.

## Q1. Import NumPy as `np`.

In [2]:
import numpy as np

## Q2. Create a NumPy array: `[10, 20, 30, 40, 50]`.

In [3]:
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


## Q3. Add `5` to every element of the above array.

In [4]:
print(arr + 5)

[15 25 35 45 55]


## Q4. Multiply every element by `2`.

In [5]:
print(arr * 2)

[ 20  40  60  80 100]


## Q5. Create the following 3×3 array:
```
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q6. Add `10` to every element of the above array.

In [7]:
print(matrix + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


## Q7. Multiply every element of the above array by `3`.

In [9]:
print(matrix * 3)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


## Q8. Create `arr = np.array([1,2,3])` and add it to:
```
[[10,20,30],
 [40,50,60]]
```

In [10]:
arr = np.array([1,2,3])
matrix = np.array([[10,20,30],[40,50,60]])
print(matrix + arr)

[[11 22 33]
 [41 52 63]]


## Q9. Create `arr = np.array([5,10,15,20,25])` and find its **sum**.

In [11]:
arr = np.array([5,10,15,20,25])
print(np.sum(arr))

75


## Q10. Find the **mean** of the above array.

In [12]:
arr = np.array([5,10,15,20,25])
print(np.mean(arr))

15.0


## Q11. Find the **maximum** and **minimum** value.

In [13]:
arr = np.array([5,10,15,20,25])
print(np.max(arr))
print(np.min(arr))

25
5


## Q12. Find the **standard deviation**.

In [14]:
print(np.std(arr))

7.0710678118654755


## Q13. Create:
```
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
```

In [15]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


## Q14. Find the **row-wise sum** (`axis=1`).

In [16]:
row_sum = np.sum(arr,axis = 1)
print(row_sum)

[ 60 150 240]


## Q15. Find the **column-wise sum** (`axis=0`).

In [17]:
column_sum = np.sum(arr,axis = 1)
print(column_sum)

[ 60 150 240]
